// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notif

import (
	"github.com/google/wire"
	"github.com/mnhjddn/go-notif-producer/app"
)

// Injectors from wire.go:

func InjectRoutes() (*Routes, error) {
	appConfig := app.ProvideAppConfig()
	db := app.ProvideMySQL(appConfig)
	publisher := app.ProvidePublisher(appConfig)
	repository := NewRepository(db, publisher, appConfig)
	service := NewService(repository)
	delivery := NewDelivery(service)
	routes := NewRoutes(delivery)
	return routes, nil
}

// wire.go:

var (
	ModuleSets = wire.NewSet(
		NewRepository,
		NewService, wire.Bind(new(IRepository), new(*Repository)), wire.Bind(new(IService), new(*Service)), NewDelivery,
		NewRoutes)
)
