// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notif

import (
	"github.com/google/wire"
	"github.com/mnhjddn/go-notif-consumer/app"
	"github.com/mnhjddn/go-notif-consumer/infra"
)

// Injectors from wire.go:

func InjectBroker() (*Broker, error) {
	appConfig := app.ProvideAppConfig()
	db := app.ProvideMySQL(appConfig)
	repository := NewRepository(db)
	mailer := infra.NewMailer(appConfig)
	service := NewService(repository, mailer)
	subscriber := app.ProvideSubscriber(appConfig)
	consumer := NewConsumer(service, subscriber)
	broker := NewBroker(consumer, appConfig)
	return broker, nil
}

// wire.go:

var (
	ModuleSets = wire.NewSet(infra.NewMailer, NewRepository,
		NewService, wire.Bind(new(infra.IMailer), new(*infra.Mailer)), wire.Bind(new(IRepository), new(*Repository)), wire.Bind(new(IService), new(*Service)), NewConsumer,
		NewBroker)
)
